### ISSUE TITLE
labels on residual curve in tutorial are incorrect

### ISSUE THREAD

**Issue by jessie-dotson** [KathrynJones1/catwoman#13]
The tutorial (https://catwoman.readthedocs.io/en/latest/tutorial.html) has a plot showing a series of curves illustrating the effect of modulating phi.  The legend on this figure is incorrect.  The legend labels the curves as being '-60 - 0', through '90- 0'.  However these residuals are created by subtracting flux_i[0] from all the other flux vectors.   The phi corresponding to flux_i[0] is -90, not 0.  (A quick check that there's something wrong is that the curve labeled '0 - 0' is *not* flat! )

**Comment by KathrynJones1** [comment]
Ah yes thank you for finding this! I've fixed the legend in the figure so it's now correct (and a bit clearer) :)
