### ISSUE TITLE
`CHANGELOG.rst` and `INSTALL` still refer to `batman`

### ISSUE THREAD

**Issue by barentsen** [KathrynJones1/catwoman#3]
Opened in relation to openjournals/joss-reviews#2382.

I noticed that `CHANGELOG.rst` and `INSTALL` in the root directory still belong to `batman`.  This will be confusing for users.

I recommend removing or updating these files.

Note:
* A `CHANGELOG` file is definitely very useful to have.  I recommend emptying the current one and starting a new one from scratch to log any future changes to `catwoman`.
* The `INSTALL` instructions for building the package from source could potentially be included in the online docs instead of the `INSTALL` file.

**Comment by KathrynJones1** [comment]
Thank you for your recommendation! I've updated the `CHANGELOG` so that it now refers to recent `catwoman` changes. I've also removed the `INSTALL` file and added a section in the online docs to refer to this.

**Comment by barentsen** [comment]
Awesome :+1:
