### ISSUE TITLE
Tutorial typo:  Undefined variable in definition of power2 limb darkening law

### ISSUE THREAD

**Issue by jessie-dotson** [KathrynJones1/catwoman#8]
In the equations defining the available limb darkening laws, the equation for power2 includes mu_2, however mu_2 isn't defined anywhere.  Similarly, this equation specifies that mu_2 is raised to the power of c -- but all the other c's are subscripted.  (By mu_2 I mean mu subscript 2...)

**Comment by KathrynJones1** [comment]
Ah yes apologies this should have been mu^{c_2}, I've fixed this now!
